blank_issues_enabled: false
contact_links:
  - name: "SUPPORT ☛ The Discussions feature of this repository"
    url: https://github.com/magit/forge/discussions
    about: Please search, ask and answer questions here.
  - name: "SUPPORT ☛ Emacs StackExchange"
    url: https://emacs.stackexchange.com/questions/tagged/forge
    about: Another place to search, ask and answer questions.
  - name: "SUPPORT ☛ Emacs Reddit"
    url: https://www.reddit.com/r/emacs
    about: Another place to search, ask and answer questions.
  - name: "Forge FAQ"
    url: https://magit.vc/manual/forge/FAQ.html
    about: It might be that many others had the same question.
  - name: "Forge Manual"
    url: https://magit.vc/manual/forge/#Top
    about: The fine manual may also be of use.
